struct User {
  email        string
  full_name    string
  id           int [optional]
  phone_number string
}

interface UserService {
  create_user(properties User) User
  delete_user_by_id(id int) bool
  get_all_users() []User
  get_user_by_id(id int) User
  update_user_by_id(id int, properties User) User
}
