struct UserProperties {
  email        string
  full_name    string
  phone_number string
  id           int [optional]
}

interface UserService {
  create_user(properties UserProperties) UserProperties
  delete_user_by_id(user_id int) bool
  get_all_users() []UserProperties
  get_user_by_id(user_id int) UserProperties
  update_user_by_id(user_id int, properties UserProperties) UserProperties
}
